# Generated by Django 4.0.10 on 2023-08-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advs',
            table='advertisements',
        ),
    ]
